---
- set_fact:
    project_deployment_util: /usr/local/bin/setup_{{ deployment_project }}.sh
- file:
    src: files/deploy_from_git.sh
    dest: /usr/local/bin/deploy_from_git.sh
    mode: 0755
- template:
    src: deploy_project.sh
    dest: "{{ project_deployment_util }}"
    mode: 0755
- include: cron.yml
  when: deployment_use_cron
- include: user.yml
  when: deployment_dedicated_user
